title: aznets
description: Just another cool site
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github:
  ml_url: https://aznets.github.io/ml/
  dl_url: https://aznets.github.io/dl/
  radiomics_url: https://aznets.github.io/radiomics/
  research_url: https://aznets.github.io/research/
